    version: "3.7"

    services:

        Service_1:
            build: ./Service_1
            image: sipeki/service_1
            container_name: service_1
            ports:
                - "5000:5000"
            networks:
                - sfia2_network
            
            depends_on:
                - Service_4
                - Service_2
                - Service_3
    
        Service_2:
            build: ./Service_2
            image: sipeki/service_2
            container_name: service_2
            networks:
                - sfia2_network

        Service_3:
            build: ./Service_3
            image: sipeki/service_3
            container_name: Service_3
            networks:
                - sfia2_network

        Service_4:
            build: ./Service_4
            image: sipeki/service_4
            container_name: service_4
            networks:
                - sfia2_network

    networks:
        sfia2_network:
            driver: bridge
            name: sfia2_network  
        another_network:
            driver: bridge
        
            