---
  - name: Install Docker-CE on Worker
    hosts: swarm-worker
    become: true
    roles:
      - docker-installation 
  
  - name: Install Docker-CE on Manager
    hosts: localhost
    connection: local
    become: true
    roles:
      - docker-installation
      - docker-swarm-init
  
  - name: Worker Join 
    hosts: swarm-worker
    become: true
    roles:
      - docker-swarm-join