---
- name: Install Docker-CE on Worker
  hosts: sfia2_swarm_3
  become: true
  roles:
    - docker-installation 
    - docker-swarm-join
    
- name: Install Docker-CE on Manager
  hosts: localhost
  connection: local
  become: true
  roles:
    - docker-installation
    - docker-swarm-init
