---
- name: NGINX
  hosts: swarm-worker
  become: true
  tasks:
  - name: install NGINX
    apt: 
      name: nginx
      state: latest
      update_cache: true
  - name: Start NGINX
    service: 
      name: nginx 
      state: started