apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
spec:
  selector:
    matchLabels:
      app: service-1
  replicas: 3
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
      - name: service_1
        image: sipeki/service_1
        ports:
        - containerPort: 5000