apiVersion: v1
kind: Service
metadata:
  name: service-4
spec:
  selector:
    app: service-4
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-4
spec:
  selector:
    matchLabels:
      app: service-4
  replicas: 3
  template:
    metadata:
      labels:
        app: service-4
    spec:
      hostname: service-4
      containers:
      - name: service-4
        image: sipeki/service_4
        ports:
        - containerPort: 5003