apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
  selector:
    app: service-2
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-3
spec:
  selector:
    matchLabels:
      app: service-3
  replicas: 3
  template:
    metadata:
      labels:
        app: service-3
    spec:
      containers:
      - name: service-3
        image: sipeki/service_2
        ports:
        - containerPort: 5003