apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    app: service-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
spec:
  selector:
    matchLabels:
      app: service-1
  replicas: 3
  template:
    metadata:
      labels:
        app: service-1
    spec:
      hostname: service-1
      containers:
      - name: service-1
        image: sipeki/service_1
        ports:
        - containerPort: 5000